### ISSUE TITLE
使用后新版QQ无法显示中文

### ISSUE THREAD

**Issue by Andor233** [m13253/FaithType#2]
![image](https://github.com/m13253/FaithType/assets/16273755/ba209fbc-103a-4cbb-9fbc-429e2f9b19ec)

**Comment by m13253** [comment]
I can’t run QQ on my workstation due to security and privacy reasons, thus unable to provide any help.
However, I will leave this issue open, in case anyone else can help.

**Comment by Andor233** [comment]
Actually, On MS itself own apps
![image](https://github.com/m13253/FaithType/assets/16273755/a0224afd-4118-46b6-8e17-3c25475b2a4c)
<Get Help>

**Comment by Andor233** [comment]
> 

Not only QQ

**Comment by Andor233** [comment]
Both of them it based on electron, but vscode works fine

**Comment by m13253** [comment]
Have you tried: restart the system → uninstall → restart again → install → restart 3rd time?

**Comment by m13253** [comment]
> Both of them it based on electron, but vscode works fine

Do you also have MacType installed?
If so, try disabling it or add an exception rule to its configuration file.

MacType is known to cause issues with some (bot not all) Electron-based applications.
A list of affected applications are:
* Can’t start: Slack, Element.
* UI sometimes breaks: VS Code, Notion, Discord, Navigraph Charts, iZotope RX.

Other apps that are known to conflict with MacType:
* OneDrive Client, Forza Horizon 5, Riot Launcher.

**Comment by Andor233** [comment]
1. Tried.
2. No mactype installed.

**Comment by Andor233** [comment]
It seems like if you change the registry of msyh.ttc to any other, it will happen. Not related to the patched font.

I just replace the patched font into C:\windows\fonts, it works fine

**Comment by m13253** [comment]
> Actually, On MS itself own apps

What’s this app? How can I access this screen?

**Comment by m13253** [comment]
> It seems like if you change the registry of msyh.ttc to any different, it will happen. Not related to the pathed font.

The most likely cause is the system’s font cache being outdated.
Normally restarting the system fixes the issue. (But it doesn’t seem to fix your machine.)

Alternatively you can try to right-click install a random font with whatever name, then uninstall that font.
This will also trigger a font cache rebuild.

**Comment by Andor233** [comment]
> 

Get Help
Simply open it if your system language is Chinese(Or maybe you can input Chinese if you are not).

> Alternatively you can try to right-click install a random font with whatever name, then uninstall that font.

Not working

**Comment by m13253** [comment]
> Get Help

Reproduced on my side.

This app is an XAML + Edge WebView2 app.
The mojibake happens inside the Edge WebView2 frame.

I currently have no idea about this issue, as there is no issue with Edge itself.
Probably the CSS inside the Get Help app has some issue causing wrong fallback path or something.

![Screenshot 2023-09-01 190057](https://github.com/m13253/FaithType/assets/1808930/dc79be96-6352-411b-b0af-86c35aa5b5b1)

**Comment by m13253** [comment]
> I just replace the patched font into C:\windows\fonts, it works fine

This should work. But you have the risk of not passing Windows Resource Protection (sfc.exe).

**Comment by m13253** [comment]
The new version should fix the Get Help app.
I can’t confirm whether it fixes QQ.

Please use the Auto-Uninstall script first, before you reinstall.

**Comment by Andor233** [comment]
Confirmed.
